In [ ]:
!python -m pip install pennylane numpy scipy pandas plotly tqdm nbformat


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.2/57.2 kB 3.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 77.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 934.3/934.3 kB 59.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 80.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 86.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.9/167.9 kB 14.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.8/8.8 MB 117.1 MB/s eta 0:00:00


In [ ]:
import pennylane as qml
import numpy as np
import scipy
import pandas as pd
import plotly
from tqdm import tqdm

print("All required libraries imported successfully!")


/usr/local/lib/python3.12/dist-packages/pennylane/__init__.py:209: RuntimeWarning: PennyLane is not yet compatible with JAX versions > 0.6.2. You have version 0.7.2 installed. Please downgrade JAX to 0.6.2 to avoid runtime errors using python -m pip install jax~=0.6.0 jaxlib~=0.6.0
  warnings.warn(


All required libraries imported successfully!


In [ ]:
import sys
import platform

print("Python version:", sys.version)
print("Platform:", platform.platform())


Python version: 3.12.12 (main, Oct 10 2025, 08:52:57) [GCC 11.4.0]
Platform: Linux-6.6.105+-x86_64-with-glibc2.35


In [ ]:
dev = qml.device("default.qubit", wires=1)

@qml.qnode(dev)
def test_circuit():
    qml.Hadamard(wires=0)
    return qml.state()

print(test_circuit())


[0.70710678+0.j 0.70710678+0.j]


Environment Setup:
The project environment was set up using Google Colab.
Required libraries including PennyLane, NumPy, SciPy, Pandas, Plotly, and TQDM were installed and verified successfully.
A single-qubit test circuit was executed to confirm correct simulator behavior.


Born Rule
In quantum mechanics, the outcome of a measurement is probabilistic.
The Born rule gives the probability of obtaining a measurement outcome.

Formula:

 *p*(k)=Tr(Mk*p*)

ρ (rho) → quantum state (unknown cheez jo hum nikalna chahte hain)

Mₖ → measurement ka ek possible outcome

Trace → diagonal ka sum

p(k) → outcome k aane ki probability

If the qubit is in state |0⟩ and we measure in the Z basis:

Probability of outcome |0⟩ = 1

Probability of outcome |1⟩ = 0

This is correctly predicted by the Born rule.

### Pauli Projective Measurements

Pauli projective measurements are a standard measurement scheme for single-qubit systems. They correspond to measurements along the X, Y, and Z axes of the Bloch sphere.

- Z-basis measurement distinguishes between |0⟩ and |1⟩.
- X-basis measurement distinguishes between |+⟩ and |−⟩.
- Y-basis measurement provides information about the relative phase of the quantum state.

By combining measurements from all three bases, the complete single-qubit quantum state can be reconstructed.


### SIC POVM (Overview)

Symmetric Informationally Complete Positive Operator-Valued Measures (SIC POVMs) provide an alternative measurement framework in which a minimal set of measurement outcomes is sufficient to fully characterize a quantum state.

While SIC POVMs are theoretically efficient, they are more complex to implement and require non-standard measurement bases.


### Measurement Model Choice

In this work, Pauli projective measurements were chosen due to their simplicity, interpretability, and widespread support in quantum simulators. SIC POVMs were reviewed conceptually but were not implemented in Week 1.


### Measurement Operator Completeness

For a valid measurement model, the measurement operators must satisfy the completeness condition:

∑k Mk = I

This ensures that the probabilities of all measurement outcomes sum to one.


In [ ]:
import numpy as np

M0 = np.array([[1, 0],
               [0, 0]])

M1 = np.array([[0, 0],
               [0, 1]])

identity = np.eye(2)

print("Completeness check (M0 + M1 = I):")
print(np.allclose(M0 + M1, identity))


Completeness check (M0 + M1 = I):
True


In [ ]:
import pennylane as qml
import numpy as np


In [ ]:
dev = qml.device("default.qubit", wires=1)


In [ ]:
@qml.qnode(dev)
def zero_state():
    return qml.state()

zero_state()


array([1.+0.j, 0.+0.j])

In [ ]:
@qml.qnode(dev)
def one_state():
    qml.PauliX(wires=0)
    return qml.state()

one_state()


array([0.+0.j, 1.+0.j])

In [ ]:
@qml.qnode(dev)
def plus_state():
    qml.Hadamard(wires=0)
    return qml.state()

plus_state()


array([0.70710678+0.j, 0.70710678+0.j])

In [ ]:
@qml.qnode(dev)
def minus_state():
    qml.PauliX(wires=0)
    qml.Hadamard(wires=0)
    return qml.state()

minus_state()


array([ 0.70710678+0.j, -0.70710678+0.j])

In [ ]:
@qml.qnode(dev)
def phase_state():
    qml.Hadamard(wires=0)
    qml.S(wires=0)
    return qml.state()

phase_state()


array([0.70710678+0.j        , 0.        +0.70710678j])

Building density matrix

In [ ]:
def density_matrix(state):
    return np.outer(state, np.conj(state))


In [ ]:
psi = plus_state()
rho_plus = density_matrix(psi)
rho_plus


array([[0.5+0.j, 0.5+0.j],
       [0.5+0.j, 0.5+0.j]])

In [ ]:
import os
os.makedirs("data/single_qubit", exist_ok=True)

np.save("data/single_qubit/rho_plus.npy", rho_plus)


### Reference State Preparation

- |0⟩ state was prepared with no gates applied.
- |1⟩ state was prepared using a Pauli-X gate.
- |+⟩ state was prepared using a Hadamard gate.
- |−⟩ state was prepared using a Pauli-X gate followed by a Hadamard gate.
- The phase-offset state (|0⟩ + i|1⟩)/√2 was prepared using a Hadamard gate followed by an S gate.


Here are the devices for measurement

In [ ]:
dev = qml.device("default.qubit", wires=1, shots=1000)


/usr/local/lib/python3.12/dist-packages/pennylane/devices/device_api.py:193: PennyLaneDeprecationWarning: Setting shots on device is deprecated. Please use the `set_shots` transform on the respective QNode instead.
  warnings.warn(


Z measurement

In [ ]:


@qml.qnode(dev)
def plus_Z():
    qml.Hadamard(wires=0)  # prepare |+>
    return qml.sample(qml.PauliZ(0))

samples = plus_Z()


In [ ]:
unique, counts = np.unique(samples, return_counts=True)
dict(zip(unique, counts))


{np.float64(-1.0): np.int64(498), np.float64(1.0): np.int64(502)}

In [ ]:
np.save("data/single_qubit/plus_Z.npy", samples)


X basis measurement

In [ ]:
@qml.qnode(dev)
def plus_X():
    qml.Hadamard(wires=0)  # prepare |+>
    qml.Hadamard(wires=0)  # rotate basis
    return qml.sample(qml.PauliZ(0))

samples = plus_X()
np.save("data/single_qubit/plus_X.npy", samples)


Y Basis measurement

In [ ]:
@qml.qnode(dev)
def plus_Y():
    qml.Hadamard(wires=0)  # prepare |+>
    qml.adjoint(qml.S)(wires=0)
    qml.Hadamard(wires=0)
    return qml.sample(qml.PauliZ(0))

samples = plus_Y()
np.save("data/single_qubit/plus_Y.npy", samples)


Counts->Probabilites

In [ ]:
def probabilities(samples):
    unique, counts = np.unique(samples, return_counts=True)
    probs = dict(zip(unique, counts / len(samples)))
    return probs


In [ ]:
probs_Z = probabilities(np.load("data/single_qubit/plus_Z.npy"))


Finding bloch vector

Z = p(0)-p(1)

In [ ]:
def expectation(probs):
    return probs.get(1, 0) - probs.get(-1, 0)


Reconstructing density matrix

Formula for single cubit
ρ=1/2​(I+xσx​+yσy​+zσz​)

In [ ]:
samples_X = np.load("data/single_qubit/plus_X.npy")
samples_Y = np.load("data/single_qubit/plus_Y.npy")
samples_Z = np.load("data/single_qubit/plus_Z.npy")


In [ ]:
def expectation_value(samples):
    return np.mean(samples)


In [ ]:
x = expectation_value(samples_X)
y = expectation_value(samples_Y)
z = expectation_value(samples_Z)

print("Bloch vector:")
print("x =", x, "y =", y, "z =", z)


Bloch vector:
x = 1.0 y = 0.028 z = 0.004


In [ ]:
I = np.eye(2)
sx = np.array([[0, 1], [1, 0]])
sy = np.array([[0, -1j], [1j, 0]])
sz = np.array([[1, 0], [0, -1]])

rho = 0.5 * (I + x*sx + y*sy + z*sz)
rho


array([[0.502+0.j   , 0.5  -0.014j],
       [0.5  +0.014j, 0.498+0.j   ]])

In [ ]:
import numpy as np
import plotly.graph_objects as go
from fractions import Fraction

_CUBE_FACES = (
    (0, 1, 2), (0, 2, 3),
    (4, 5, 6), (4, 6, 7),
    (0, 1, 5), (0, 5, 4),
    (1, 2, 6), (1, 6, 5),
    (2, 3, 7), (2, 7, 6),
    (3, 0, 4), (3, 4, 7)
)

def _phase_to_pi_string(angle_rad: float) -> str:
    if np.isclose(angle_rad, 0.0):
        return "0"
    multiple = angle_rad / np.pi
    frac = Fraction(multiple).limit_denominator(16)
    numerator = frac.numerator
    denominator = frac.denominator
    sign = "-" if numerator < 0 else ""
    numerator = abs(numerator)
    if denominator == 1:
        magnitude = f"{numerator}" if numerator != 1 else ""
    else:
        magnitude = f"{numerator}/{denominator}"
    return f"{sign}{magnitude}π" if magnitude else f"{sign}π"

def plot_density_matrix_histogram(rho, basis_labels=None,
                                  title="Density matrix (|ρ_ij| as bar height, phase as color)"):
    rho = np.asarray(rho)
    dim = rho.shape[0]

    mags = np.abs(rho)
    phases = np.angle(rho)

    if basis_labels is None:
        basis_labels = [str(i) for i in range(dim)]

    meshes = []
    colorbar_added = False

    for i in range(dim):
        for j in range(dim):
            height = mags[i, j]
            phase = phases[i, j]
            x0, x1 = i - 0.45, i + 0.45
            y0, y1 = j - 0.45, j + 0.45

            vertices = (
                (x0, y0, 0.0), (x1, y0, 0.0), (x1, y1, 0.0), (x0, y1, 0.0),
                (x0, y0, height), (x1, y0, height),
                (x1, y1, height), (x0, y1, height)
            )

            x_coords, y_coords, z_coords = zip(*vertices)
            i_idx, j_idx, k_idx = zip(*_CUBE_FACES)

            mesh = go.Mesh3d(
                x=x_coords,
                y=y_coords,
                z=z_coords,
                i=i_idx,
                j=j_idx,
                k=k_idx,
                intensity=[phase] * len(vertices),
                colorscale="HSV",
                cmin=-np.pi,
                cmax=np.pi,
                showscale=not colorbar_added,
                colorbar=dict(
                    title="phase",
                    tickvals=[-np.pi, -np.pi/2, 0, np.pi/2, np.pi],
                    ticktext=["-π", "-π/2", "0", "π/2", "π"]
                ) if not colorbar_added else None,
                opacity=1.0
            )
            meshes.append(mesh)
            colorbar_added = True

    fig = go.Figure(data=meshes)
    fig.update_layout(
        scene=dict(
            xaxis=dict(title="i", tickvals=list(range(dim)), ticktext=basis_labels),
            yaxis=dict(title="j", tickvals=list(range(dim)), ticktext=basis_labels),
            zaxis=dict(title="|ρ_ij|")
        ),
        title=title
    )

    fig.show()


In [ ]:
plot_density_matrix_histogram(rho, title="Reconstructed |+> state")


In [ ]:
rho_true = np.load("data/single_qubit/rho_plus.npy")
rho_recon = rho   # reconstructed one


In [ ]:
def fidelity(rho_true, rho_est):
    return np.real(np.trace(rho_true @ rho_est))


In [ ]:
F = fidelity(rho_true, rho_recon)
print("Fidelity =", F)


Fidelity = 0.9999999999999998


In [ ]:
def trace_distance(rho1, rho2):
    diff = rho1 - rho2
    eigvals = np.linalg.eigvals(diff)
    return 0.5 * np.sum(np.abs(eigvals))


Result Table

In [ ]:
import pandas as pd

results = pd.DataFrame({
    "State": ["|+>"],
    "Fidelity": [F]
})

results


State  Fidelity
0   |+>       1.0

In [ ]:
plot_density_matrix_histogram(rho_recon, title="Reconstructed |+> state")


### Error Analysis

The primary sources of error in the reconstructed density matrices include finite shot noise due to a limited number of measurement samples, statistical fluctuations in measurement outcomes, and basis rotation errors during measurement. Increasing the number of shots and using more advanced reconstruction techniques such as maximum likelihood estimation could further improve accuracy.


### Reflection and Future Work

This week focused on building a basic and reproducible single-qubit quantum state tomography pipeline. The main challenges involved understanding quantum measurements and implementing basis rotations correctly. In future work, the pipeline can be extended to multi-qubit systems, random circuits, and more advanced reconstruction methods such as maximum likelihood estimation.


In [ ]:
from typing import Dict, Any
import pathlib

def build_measurement_model(config_path: pathlib.Path) -> Dict[str, Any]:
    """
    Stub for constructing or loading the measurement operators you plan to use.
    Populate the return value with operator definitions, normalization checks, and metadata.
    """
    # TODO: implement SIC POVM or Pauli projective operator assembly here.
    raise NotImplementedError("Create your measurement operator assembly here.")

In [ ]:
import numpy as np
import plotly.graph_objects as go
from fractions import Fraction

_CUBE_FACES = (
    (0, 1, 2), (0, 2, 3),  # bottom
    (4, 5, 6), (4, 6, 7),  # top
    (0, 1, 5), (0, 5, 4),
    (1, 2, 6), (1, 6, 5),
    (2, 3, 7), (2, 7, 6),
    (3, 0, 4), (3, 4, 7)
 )

def _phase_to_pi_string(angle_rad: float) -> str:
    """Format a phase angle as a simplified multiple of π."""
    if np.isclose(angle_rad, 0.0):
        return "0"
    multiple = angle_rad / np.pi
    frac = Fraction(multiple).limit_denominator(16)
    numerator = frac.numerator
    denominator = frac.denominator
    sign = "-" if numerator < 0 else ""
    numerator = abs(numerator)
    if denominator == 1:
        magnitude = f"{numerator}" if numerator != 1 else ""
    else:
        magnitude = f"{numerator}/{denominator}"
    return f"{sign}{magnitude}π" if magnitude else f"{sign}π"

def plot_density_matrix_histogram(rho, basis_labels=None, title="Density matrix (|ρ_ij| as bar height, phase as color)"):
    """Render a density matrix as a grid of solid histogram bars with phase coloring."""
    rho = np.asarray(rho)
    if rho.ndim != 2 or rho.shape[0] != rho.shape[1]:
        raise ValueError("rho must be a square matrix")

    dim = rho.shape[0]
    mags = np.abs(rho)
    phases = np.angle(rho)
    x_vals = np.arange(dim)
    y_vals = np.arange(dim)

    if basis_labels is None:
        basis_labels = [str(i) for i in range(dim)]

    meshes = []
    colorbar_added = False
    for i in range(dim):
        for j in range(dim):
            height = mags[i, j]
            phase = phases[i, j]
            x0, x1 = i - 0.45, i + 0.45
            y0, y1 = j - 0.45, j + 0.45
            vertices = (
                (x0, y0, 0.0), (x1, y0, 0.0), (x1, y1, 0.0), (x0, y1, 0.0),
                (x0, y0, height), (x1, y0, height), (x1, y1, height), (x0, y1, height)
            )
            x_coords, y_coords, z_coords = zip(*vertices)
            i_idx, j_idx, k_idx = zip(*_CUBE_FACES)
            phase_pi = _phase_to_pi_string(phase)
            mesh = go.Mesh3d(
                x=x_coords,
                y=y_coords,
                z=z_coords,
                i=i_idx,
                j=j_idx,
                k=k_idx,
                intensity=[phase] * len(vertices),
                colorscale="HSV",
                cmin=-np.pi,
                cmax=np.pi,
                showscale=not colorbar_added,
                colorbar=dict(
                    title="phase ",
                    tickvals=[-np.pi, -np.pi/2, 0, np.pi/2, np.pi],
                    ticktext=["-π", "-π/2", "0", "π/2", "π"]
                ) if not colorbar_added else None,
                opacity=1.0,
                flatshading=False,
                hovertemplate=
                    f"i={i}, j={j}<br>|ρ_ij|={height:.3f}<br>arg(ρ_ij)={phase_pi}<extra></extra>",
                lighting=dict(ambient=0.6, diffuse=0.7)
            )
            meshes.append(mesh)
            colorbar_added = True

    fig = go.Figure(data=meshes)
    fig.update_layout(
        scene=dict(
            xaxis=dict(
                title="i",
                tickmode="array",
                tickvals=x_vals,
                ticktext=basis_labels
            ),
            yaxis=dict(
                title="j",
                tickmode="array",
                tickvals=y_vals,
                ticktext=basis_labels
            ),
            zaxis=dict(title="|ρ_ij|"),
            aspectratio=dict(x=1, y=1, z=0.7)
        ),
        title=title,
        margin=dict(l=0, r=0, b=0, t=40)
    )

    fig.show()


In [ ]:
plot_density_matrix_histogram(
    rho,
    basis_labels=["0", "1"],
    title="Reconstructed |+> state"
)


Constructing more plots

In [ ]:
@qml.qnode(dev)
def zero_Z():
    return qml.sample(qml.PauliZ(0))

samples_Z = zero_Z()
z0 = np.mean(samples_Z)


In [ ]:
@qml.qnode(dev)
def zero_X():
    qml.Hadamard(wires=0)
    return qml.sample(qml.PauliZ(0))

samples_X = zero_X()
x0 = np.mean(samples_X)


In [ ]:
@qml.qnode(dev)
def zero_Y():
    qml.adjoint(qml.S)(wires=0)
    qml.Hadamard(wires=0)
    return qml.sample(qml.PauliZ(0))

samples_Y = zero_Y()
y0 = np.mean(samples_Y)


In [ ]:
I = np.eye(2)
sx = np.array([[0, 1], [1, 0]])
sy = np.array([[0, -1j], [1j, 0]])
sz = np.array([[1, 0], [0, -1]])

rho_zero_recon = 0.5 * (I + x0*sx + y0*sy + z0*sz)
rho_zero_recon


array([[ 1.   +0.j   , -0.017-0.032j],
       [-0.017+0.032j,  0.   +0.j   ]])

In [ ]:
plot_density_matrix_histogram(
    rho_zero_recon,
    basis_labels=["0", "1"],
    title="Reconstructed |0> state"
)


### Reflection and Future Work

This project implemented a complete single-qubit quantum state tomography pipeline using Pauli measurements. The main challenges involved understanding measurement basis rotations and statistical noise. In future work, this pipeline can be extended to multi-qubit systems, random circuits, and more advanced reconstruction techniques such as maximum likelihood estimation.


### Visualization Note

Density matrix visualizations were generated using Plotly during execution of the notebook. Due to interactive rendering, plots are best viewed by running the corresponding cells.
